/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LinkedEmailPublic {
  'provider' : string,
  'isLinked' : boolean,
  'emailAddress' : string,
}
export interface LinkedPhonePublic {
  'isLinked' : boolean,
  'phoneNumber' : string,
}
export interface ProtectionSettingsPublic {
  'aiIntel' : boolean,
  'silentScan' : boolean,
  'smsProtection' : boolean,
  'emailProtection' : boolean,
  'browserProtection' : boolean,
}
export interface ScanEntry {
  'id' : bigint,
  'url' : string,
  'result' : ScanResult,
  'scanType' : ScanType,
  'timestamp' : bigint,
  'confidence' : bigint,
}
export type ScanResult = { 'safe' : null } |
  { 'spam' : null } |
  { 'phishing' : null } |
  { 'malware' : null };
export type ScanType = { 'qr' : null } |
  { 'url' : null } |
  { 'email' : null };
export interface Stats {
  'totalScanned' : bigint,
  'totalWarnings' : bigint,
  'totalBlocked' : bigint,
}
export interface ThreatAlertPublic {
  'id' : bigint,
  'url' : string,
  'source' : ThreatSource,
  'isRead' : boolean,
  'threatName' : string,
  'threatType' : ThreatType,
  'timestamp' : bigint,
  'riskScore' : bigint,
}
export type ThreatSource = { 'qr' : null } |
  { 'sms' : null } |
  { 'url' : null } |
  { 'email' : null };
export type ThreatType = { 'spam' : null } |
  { 'phishing' : null } |
  { 'malware' : null };
export interface _SERVICE {
  'getAlerts' : ActorMethod<[], Array<ThreatAlertPublic>>,
  'getLinkedEmail' : ActorMethod<[], LinkedEmailPublic>,
  'getLinkedPhone' : ActorMethod<[], LinkedPhonePublic>,
  'getProtectionSettings' : ActorMethod<[], ProtectionSettingsPublic>,
  'getScanHistory' : ActorMethod<[], Array<ScanEntry>>,
  'getSecurityScore' : ActorMethod<[], bigint>,
  'getStats' : ActorMethod<[], Stats>,
  'getUnreadAlertsCount' : ActorMethod<[], bigint>,
  'linkEmail' : ActorMethod<[string, string], undefined>,
  'linkPhone' : ActorMethod<[string], undefined>,
  'markAlertRead' : ActorMethod<[bigint], undefined>,
  'markAllAlertsRead' : ActorMethod<[], undefined>,
  'scanEmail' : ActorMethod<[string], ScanEntry>,
  'scanQr' : ActorMethod<[string], ScanEntry>,
  'scanUrl' : ActorMethod<[string], ScanEntry>,
  'simulateEmailThreat' : ActorMethod<[string, string], ThreatAlertPublic>,
  'unlinkEmail' : ActorMethod<[], undefined>,
  'unlinkPhone' : ActorMethod<[], undefined>,
  'updateProtectionSettings' : ActorMethod<
    [ProtectionSettingsPublic],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];