/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ThreatSource = IDL.Variant({
  'qr' : IDL.Null,
  'sms' : IDL.Null,
  'url' : IDL.Null,
  'email' : IDL.Null,
});
export const ThreatType = IDL.Variant({
  'spam' : IDL.Null,
  'phishing' : IDL.Null,
  'malware' : IDL.Null,
});
export const ThreatAlertPublic = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'source' : ThreatSource,
  'isRead' : IDL.Bool,
  'threatName' : IDL.Text,
  'threatType' : ThreatType,
  'timestamp' : IDL.Int,
  'riskScore' : IDL.Nat,
});
export const LinkedEmailPublic = IDL.Record({
  'provider' : IDL.Text,
  'isLinked' : IDL.Bool,
  'emailAddress' : IDL.Text,
});
export const LinkedPhonePublic = IDL.Record({
  'isLinked' : IDL.Bool,
  'phoneNumber' : IDL.Text,
});
export const ProtectionSettingsPublic = IDL.Record({
  'aiIntel' : IDL.Bool,
  'silentScan' : IDL.Bool,
  'smsProtection' : IDL.Bool,
  'emailProtection' : IDL.Bool,
  'browserProtection' : IDL.Bool,
});
export const ScanResult = IDL.Variant({
  'safe' : IDL.Null,
  'spam' : IDL.Null,
  'phishing' : IDL.Null,
  'malware' : IDL.Null,
});
export const ScanType = IDL.Variant({
  'qr' : IDL.Null,
  'url' : IDL.Null,
  'email' : IDL.Null,
});
export const ScanEntry = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'result' : ScanResult,
  'scanType' : ScanType,
  'timestamp' : IDL.Int,
  'confidence' : IDL.Nat,
});
export const Stats = IDL.Record({
  'totalScanned' : IDL.Nat,
  'totalWarnings' : IDL.Nat,
  'totalBlocked' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAlerts' : IDL.Func([], [IDL.Vec(ThreatAlertPublic)], ['query']),
  'getLinkedEmail' : IDL.Func([], [LinkedEmailPublic], ['query']),
  'getLinkedPhone' : IDL.Func([], [LinkedPhonePublic], ['query']),
  'getProtectionSettings' : IDL.Func([], [ProtectionSettingsPublic], ['query']),
  'getScanHistory' : IDL.Func([], [IDL.Vec(ScanEntry)], ['query']),
  'getSecurityScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUnreadAlertsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'linkEmail' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'linkPhone' : IDL.Func([IDL.Text], [], []),
  'markAlertRead' : IDL.Func([IDL.Nat], [], []),
  'markAllAlertsRead' : IDL.Func([], [], []),
  'scanEmail' : IDL.Func([IDL.Text], [ScanEntry], []),
  'scanQr' : IDL.Func([IDL.Text], [ScanEntry], []),
  'scanUrl' : IDL.Func([IDL.Text], [ScanEntry], []),
  'simulateEmailThreat' : IDL.Func(
      [IDL.Text, IDL.Text],
      [ThreatAlertPublic],
      [],
    ),
  'unlinkEmail' : IDL.Func([], [], []),
  'unlinkPhone' : IDL.Func([], [], []),
  'updateProtectionSettings' : IDL.Func([ProtectionSettingsPublic], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ThreatSource = IDL.Variant({
    'qr' : IDL.Null,
    'sms' : IDL.Null,
    'url' : IDL.Null,
    'email' : IDL.Null,
  });
  const ThreatType = IDL.Variant({
    'spam' : IDL.Null,
    'phishing' : IDL.Null,
    'malware' : IDL.Null,
  });
  const ThreatAlertPublic = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'source' : ThreatSource,
    'isRead' : IDL.Bool,
    'threatName' : IDL.Text,
    'threatType' : ThreatType,
    'timestamp' : IDL.Int,
    'riskScore' : IDL.Nat,
  });
  const LinkedEmailPublic = IDL.Record({
    'provider' : IDL.Text,
    'isLinked' : IDL.Bool,
    'emailAddress' : IDL.Text,
  });
  const LinkedPhonePublic = IDL.Record({
    'isLinked' : IDL.Bool,
    'phoneNumber' : IDL.Text,
  });
  const ProtectionSettingsPublic = IDL.Record({
    'aiIntel' : IDL.Bool,
    'silentScan' : IDL.Bool,
    'smsProtection' : IDL.Bool,
    'emailProtection' : IDL.Bool,
    'browserProtection' : IDL.Bool,
  });
  const ScanResult = IDL.Variant({
    'safe' : IDL.Null,
    'spam' : IDL.Null,
    'phishing' : IDL.Null,
    'malware' : IDL.Null,
  });
  const ScanType = IDL.Variant({
    'qr' : IDL.Null,
    'url' : IDL.Null,
    'email' : IDL.Null,
  });
  const ScanEntry = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'result' : ScanResult,
    'scanType' : ScanType,
    'timestamp' : IDL.Int,
    'confidence' : IDL.Nat,
  });
  const Stats = IDL.Record({
    'totalScanned' : IDL.Nat,
    'totalWarnings' : IDL.Nat,
    'totalBlocked' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAlerts' : IDL.Func([], [IDL.Vec(ThreatAlertPublic)], ['query']),
    'getLinkedEmail' : IDL.Func([], [LinkedEmailPublic], ['query']),
    'getLinkedPhone' : IDL.Func([], [LinkedPhonePublic], ['query']),
    'getProtectionSettings' : IDL.Func(
        [],
        [ProtectionSettingsPublic],
        ['query'],
      ),
    'getScanHistory' : IDL.Func([], [IDL.Vec(ScanEntry)], ['query']),
    'getSecurityScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUnreadAlertsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'linkEmail' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'linkPhone' : IDL.Func([IDL.Text], [], []),
    'markAlertRead' : IDL.Func([IDL.Nat], [], []),
    'markAllAlertsRead' : IDL.Func([], [], []),
    'scanEmail' : IDL.Func([IDL.Text], [ScanEntry], []),
    'scanQr' : IDL.Func([IDL.Text], [ScanEntry], []),
    'scanUrl' : IDL.Func([IDL.Text], [ScanEntry], []),
    'simulateEmailThreat' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ThreatAlertPublic],
        [],
      ),
    'unlinkEmail' : IDL.Func([], [], []),
    'unlinkPhone' : IDL.Func([], [], []),
    'updateProtectionSettings' : IDL.Func([ProtectionSettingsPublic], [], []),
  });
};

export const init = ({ IDL }) => { return []; };