/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ScanEntry {
    id: bigint;
    url: string;
    result: ScanResult;
    scanType: ScanType;
    timestamp: bigint;
    confidence: bigint;
}
export interface ProtectionSettingsPublic {
    aiIntel: boolean;
    silentScan: boolean;
    smsProtection: boolean;
    emailProtection: boolean;
    browserProtection: boolean;
}
export interface Stats {
    totalScanned: bigint;
    totalWarnings: bigint;
    totalBlocked: bigint;
}
export interface LinkedEmailPublic {
    provider: string;
    isLinked: boolean;
    emailAddress: string;
}
export interface LinkedPhonePublic {
    isLinked: boolean;
    phoneNumber: string;
}
export interface ThreatAlertPublic {
    id: bigint;
    url: string;
    source: ThreatSource;
    isRead: boolean;
    threatName: string;
    threatType: ThreatType;
    timestamp: bigint;
    riskScore: bigint;
}
export enum ScanResult {
    safe = "safe",
    spam = "spam",
    phishing = "phishing",
    malware = "malware"
}
export enum ScanType {
    qr = "qr",
    url = "url",
    email = "email"
}
export enum ThreatSource {
    qr = "qr",
    sms = "sms",
    url = "url",
    email = "email"
}
export enum ThreatType {
    spam = "spam",
    phishing = "phishing",
    malware = "malware"
}
export interface backendInterface {
    getAlerts(): Promise<Array<ThreatAlertPublic>>;
    getLinkedEmail(): Promise<LinkedEmailPublic>;
    getLinkedPhone(): Promise<LinkedPhonePublic>;
    getProtectionSettings(): Promise<ProtectionSettingsPublic>;
    getScanHistory(): Promise<Array<ScanEntry>>;
    getSecurityScore(): Promise<bigint>;
    getStats(): Promise<Stats>;
    getUnreadAlertsCount(): Promise<bigint>;
    linkEmail(provider: string, emailAddress: string): Promise<void>;
    linkPhone(phoneNumber: string): Promise<void>;
    markAlertRead(id: bigint): Promise<void>;
    markAllAlertsRead(): Promise<void>;
    scanEmail(url: string): Promise<ScanEntry>;
    scanQr(url: string): Promise<ScanEntry>;
    scanUrl(url: string): Promise<ScanEntry>;
    simulateEmailThreat(url: string, threatName: string): Promise<ThreatAlertPublic>;
    unlinkEmail(): Promise<void>;
    unlinkPhone(): Promise<void>;
    updateProtectionSettings(updated: ProtectionSettingsPublic): Promise<void>;
}
import type { ScanEntry as _ScanEntry, ScanResult as _ScanResult, ScanType as _ScanType, ThreatAlertPublic as _ThreatAlertPublic, ThreatSource as _ThreatSource, ThreatType as _ThreatType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAlerts(): Promise<Array<ThreatAlertPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLinkedEmail(): Promise<LinkedEmailPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getLinkedEmail();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLinkedEmail();
            return result;
        }
    }
    async getLinkedPhone(): Promise<LinkedPhonePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getLinkedPhone();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLinkedPhone();
            return result;
        }
    }
    async getProtectionSettings(): Promise<ProtectionSettingsPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getProtectionSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProtectionSettings();
            return result;
        }
    }
    async getScanHistory(): Promise<Array<ScanEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScanHistory();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScanHistory();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSecurityScore(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecurityScore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecurityScore();
            return result;
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUnreadAlertsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadAlertsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadAlertsCount();
            return result;
        }
    }
    async linkEmail(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkEmail(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkEmail(arg0, arg1);
            return result;
        }
    }
    async linkPhone(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkPhone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkPhone(arg0);
            return result;
        }
    }
    async markAlertRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAlertRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAlertRead(arg0);
            return result;
        }
    }
    async markAllAlertsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllAlertsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllAlertsRead();
            return result;
        }
    }
    async scanEmail(arg0: string): Promise<ScanEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.scanEmail(arg0);
                return from_candid_ScanEntry_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scanEmail(arg0);
            return from_candid_ScanEntry_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async scanQr(arg0: string): Promise<ScanEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.scanQr(arg0);
                return from_candid_ScanEntry_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scanQr(arg0);
            return from_candid_ScanEntry_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async scanUrl(arg0: string): Promise<ScanEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.scanUrl(arg0);
                return from_candid_ScanEntry_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scanUrl(arg0);
            return from_candid_ScanEntry_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async simulateEmailThreat(arg0: string, arg1: string): Promise<ThreatAlertPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.simulateEmailThreat(arg0, arg1);
                return from_candid_ThreatAlertPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.simulateEmailThreat(arg0, arg1);
            return from_candid_ThreatAlertPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlinkEmail(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlinkEmail();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlinkEmail();
            return result;
        }
    }
    async unlinkPhone(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlinkPhone();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlinkPhone();
            return result;
        }
    }
    async updateProtectionSettings(arg0: ProtectionSettingsPublic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProtectionSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProtectionSettings(arg0);
            return result;
        }
    }
}
function from_candid_ScanEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanEntry): ScanEntry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ScanResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanResult): ScanResult {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ScanType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanType): ScanType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatAlertPublic_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatAlertPublic): ThreatAlertPublic {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatSource_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatSource): ThreatSource {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatType): ThreatType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    result: _ScanResult;
    scanType: _ScanType;
    timestamp: bigint;
    confidence: bigint;
}): {
    id: bigint;
    url: string;
    result: ScanResult;
    scanType: ScanType;
    timestamp: bigint;
    confidence: bigint;
} {
    return {
        id: value.id,
        url: value.url,
        result: from_candid_ScanResult_n11(_uploadFile, _downloadFile, value.result),
        scanType: from_candid_ScanType_n13(_uploadFile, _downloadFile, value.scanType),
        timestamp: value.timestamp,
        confidence: value.confidence
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    source: _ThreatSource;
    isRead: boolean;
    threatName: string;
    threatType: _ThreatType;
    timestamp: bigint;
    riskScore: bigint;
}): {
    id: bigint;
    url: string;
    source: ThreatSource;
    isRead: boolean;
    threatName: string;
    threatType: ThreatType;
    timestamp: bigint;
    riskScore: bigint;
} {
    return {
        id: value.id,
        url: value.url,
        source: from_candid_ThreatSource_n4(_uploadFile, _downloadFile, value.source),
        isRead: value.isRead,
        threatName: value.threatName,
        threatType: from_candid_ThreatType_n6(_uploadFile, _downloadFile, value.threatType),
        timestamp: value.timestamp,
        riskScore: value.riskScore
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    safe: null;
} | {
    spam: null;
} | {
    phishing: null;
} | {
    malware: null;
}): ScanResult {
    return "safe" in value ? ScanResult.safe : "spam" in value ? ScanResult.spam : "phishing" in value ? ScanResult.phishing : "malware" in value ? ScanResult.malware : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qr: null;
} | {
    url: null;
} | {
    email: null;
}): ScanType {
    return "qr" in value ? ScanType.qr : "url" in value ? ScanType.url : "email" in value ? ScanType.email : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qr: null;
} | {
    sms: null;
} | {
    url: null;
} | {
    email: null;
}): ThreatSource {
    return "qr" in value ? ThreatSource.qr : "sms" in value ? ThreatSource.sms : "url" in value ? ThreatSource.url : "email" in value ? ThreatSource.email : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    spam: null;
} | {
    phishing: null;
} | {
    malware: null;
}): ThreatType {
    return "spam" in value ? ThreatType.spam : "phishing" in value ? ThreatType.phishing : "malware" in value ? ThreatType.malware : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ThreatAlertPublic>): Array<ThreatAlertPublic> {
    return value.map((x)=>from_candid_ThreatAlertPublic_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScanEntry>): Array<ScanEntry> {
    return value.map((x)=>from_candid_ScanEntry_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
